Add calendar plugin
anticrm/platform pull request #354
Opened 2021-04-06 11:05 UTC by ArtyomSavchenko

https://user-images.githubusercontent.com/11941313/113701552-83174080-9702-11eb-94c7-8ff1179e15b8.mov

Signed-off-by: Artyom Savchenko <armisav@gmail.com>

2021-04-07 09:29 UTC, haiodo commented on plugins/calendar/package.json
> +    "lint": "eslint src"
you need to have `lint:fix` target.

2021-04-07 09:31 UTC, haiodo commented on plugins/calendar/src/__model__.ts
> +    @EnumValue$(calendar.enum.RecurrenceType)
Will be a conflict with #355 since it has @EnumOf$() decorator instead.

2021-04-07 09:32 UTC, haiodo commented on plugins/calendar/src/components/EventsCalendar.svelte
> +  const query = createLiveQuery(calendar.class.CalendarEvent, { _space: space._id }, (docs) => {
Now it is possible to use a just `$: q = liveQuery(q,...)` as a small sugar :-)

2021-04-07 09:34 UTC, haiodo commented on plugins/workbench/src/components/internal/Application.svelte
> +    if (str === 'Calendar') return 'Add event'
@ArtyomSavchenko Please rebase, this is not required anymore and you need to use new Create extension point.

2021-04-07 09:34 UTC, haiodo requested changes
We need to wait for #355 and update to use new object creation schema.

2021-04-08 12:18 UTC, z2sx approved these changes

2021-04-08 12:19 UTC, haiodo approved these changes

2021-04-08 12:20 UTC, merged